export const libraryMapping = {
  "cEKmaenKh5Vw-r1-ftfwY": "Application\nserver",
  "94ER0Auak-kDCZjTJYjpZ": "Multi\nInstance\nserver",
  "Dg190rIIp6unC2KPOJDoU": "server",
  "QY7k-4mt0YTkScA25ceQm": "Multi Instance",
  "OLurjceIEmyYSEHSKaKQm": "Relational DB",
  "Eh2zIbKPzKeRiZdbP8W0w": "Object Storage",
  "Br68Ibk6I_T6WhK13E4Bh": "Cold Storage",
  "polD5erjpz5hYnJxh86Aw": "Document DB",
  "nFJdEKjLYcrQNirs5pbFD": "Columnar DB",
  "Y_JUkRpnRO0oARB_j7Wns": "Graph DB",
  "kmyx73d6r3HIfrWyaVgOo": "Stack\nStorage",
  "_TRhwQYRY54mP65DjT5SA": "Cache",
  "4zxuQp5IK9paoXgBsRoNA": "Auth &\n IAM",
  "pox47NS3FC9ABkChfXJMH": "DNS",
  "Kunc-BEM_w9CO0Att5ooc": "Load\nBalancer",
  "31Amcp2lWZ6SCgO_MVLBb": "Message Q",
  "StlQp8u4elrocnmZM1k9A": "Pipeline",
  "Qvzj8WVFWvQyPfL2vcTy7": "cloud",
  "0VH6czjv-GOxG6Pg3_Ddy": "CDN",
  "MzDNmYCf0c6cV2RrzuMBJ": "Archive",
  "SaUKcz7BO4GkoNJ5b9atU": "Mobile",
  "3DENSZ2r0vcP8x9Dl8f2B": "Web Application",
}
